# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a03455a8ac2cb923b0733cc542875532292ec88c604f64c425b996b99303c521c3ccea5fd4ea6489d5acb3d9b59db278f68b29a268822b63bc95917dda51a27

test:
  secret_key_base: 434503c40bdccfcc8c21ea602368d2c719b28aab3d19dccc60ad940cbfb828894366aa65eb1ad52fe6b87f31252aca39a914c9b4eb41ce1928248412fae059e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
